spring:
  flyway:
    baselineOnMigrate: true
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: plataforma-database-pool
      auto-commit: false
      connection-timeout: 30000
    url: "jdbc:postgresql://127.0.0.1:5432/rest_with_spring_boot"
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextutal_creation: true